-- DROP TABLE BOARD_T CASCADE CONSTRAINTS;
-- DROP TABLE USER_T CASCADE CONSTRAINTS;

DROP SEQUENCE PENALTY_SEQ;
DROP SEQUENCE REPORT_SEQ;
DROP SEQUENCE SCHEDULE_SEQ;
DROP SEQUENCE COMMENT_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE ATTACH_SEQ;
DROP SEQUENCE USER_SEQ;

CREATE SEQUENCE USER_SEQ NOCACHE;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;
CREATE SEQUENCE COMMENT_SEQ NOCACHE;
CREATE SEQUENCE SCHEDULE_SEQ NOCACHE;
CREATE SEQUENCE REPORT_SEQ NOCACHE;
CREATE SEQUENCE PENALTY_SEQ NOCACHE;

DROP TABLE PENALTY_T;
DROP TABLE REPORT_T;
DROP TABLE SCHEDULE_T;
DROP TABLE COMMENT_T;
DROP TABLE ATTACH_T;
DROP TABLE BOARD_T;
DROP TABLE USER_T;

CREATE TABLE USER_T (
   USER_NO      NUMBER   NOT NULL,
   USER_ID      VARCHAR2(128 BYTE)   NOT NULL UNIQUE,
   ROLE          NUMBER             DEFAULT 0 NOT NULL,
   PW            VARCHAR2(64 BYTE)  NOT NULL,
   EMAIL        VARCHAR2(100 BYTE)   NULL,
   NAME         VARCHAR2(100 BYTE) NULL,
   GENDER       VARCHAR2(5 BYTE)   NULL,
   MOBILE       VARCHAR2(20 BYTE)  NULL,
   PW_MODIFY_DT DATE               NULL,
   SIGNUP_DT    DATE               NULL,
   DELETED_DT   DATE               NULL,
    CONSTRAINT PK_USER_NO PRIMARY KEY(USER_NO)
);

CREATE TABLE BOARD_T (
   CATE_NO     NUMBER               NOT NULL,
   BOARD_NO    NUMBER               NOT NULL,
   USER_NO       NUMBER               NOT NULL,
   TITLE       VARCHAR2(1000 BYTE)   NOT NULL,
   CONTENTS    CLOB               NULL,
   HIT           NUMBER               DEFAULT 0,
   CREATE_DT   TIMESTAMP           NULL,
   MODIFY_DT   TIMESTAMP           NULL,
    CONSTRAINT PK_BOARD_NO      PRIMARY KEY (BOARD_NO),
    CONSTRAINT FK_BOARD_USER_NO FOREIGN KEY(USER_NO)
    REFERENCES USER_T(USER_NO) ON DELETE CASCADE
);

CREATE TABLE ATTACH_T (
   ATTACH_NO         NUMBER            NOT NULL,
   UPLOAD_PATH         VARCHAR2(500 BYTE) NULL,
   FILESYSTEM_NAME     VARCHAR2(500 BYTE) NULL,
   ORIGINAL_FILENAME VARCHAR2(500 BYTE) NULL,
   DOWNLOAD_COUNT     NUMBER            NULL,
   HAS_THUMBNAIL     NUMBER            NULL,
   BOARD_NO         NUMBER            NOT NULL,
    CONSTRAINT PK_ATTACH_NO PRIMARY KEY(ATTACH_NO),
    CONSTRAINT FK_ATTACH_BOARD_NO FOREIGN KEY(BOARD_NO)
    REFERENCES BOARD_T(BOARD_NO) ON DELETE CASCADE
);

CREATE TABLE COMMENT_T (
   COMMENT_NO NUMBER               NOT NULL,
   USER_NO    NUMBER               NOT NULL,
   CONTENTS   VARCHAR2(2000 BYTE)   NOT NULL,
   CREATE_DT  TIMESTAMP            NULL,
   STATE      NUMBER               NULL,
   DEPTH      NUMBER               NULL,
   GROUP_NO   NUMBER               NULL,
   BOARD_NO   NUMBER               NOT NULL,
    CONSTRAINT PK_COMMENT_NO PRIMARY KEY (COMMENT_NO),
    CONSTRAINT FK_COMMENT_USER_NO FOREIGN KEY (USER_NO)
    REFERENCES USER_T(USER_NO) ON DELETE CASCADE
);

CREATE TABLE REPORT_T (
   REPORT_NO 		  NUMBER		NOT NULL,
   REPORTER_NO		  NUMBER		NOT NULL,
   USER_NO			  NUMBER		NULL,
   BOARD_NO			  NUMBER		NULL,
   TITLE			  VARCHAR2(2000 BYTE)	NULL,
   CONTENTS			  VARCHAR2(2000 BYTE)	NULL,
   CREATE_DT		  DATE			NOT NULL,
   CONSTRAINT PK_REPORT_NO PRIMARY KEY (REPORT_NO),
   CONSTRAINT FK_REPORT_REPORTER_NO FOREIGN KEY (REPORTER_NO)
   REFERENCES USER_T(USER_NO) ON DELETE CASCADE,
   CONSTRAINT FK_REPORT_USER_NO FOREIGN KEY (USER_NO)
   REFERENCES USER_T(USER_NO) ON DELETE CASCADE
);

CREATE TABLE PENALTY_T (
   PENALTY_NO		   NUMBER		NOT NULL,
   USER_NO			   NUMBER		NOT NULL,
   NOTE				   VARCHAR2(2000 BYTE)		NULL,
   ACTIONED_DT		   DATE			NULL,
   CONSTRAINT PK_PENALTY_NO PRIMARY KEY (PENALTY_NO),
   CONSTRAINT FK_PENALTY_USER_NO FOREIGN KEY (USER_NO)
   REFERENCES USER_T(USER_NO) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE_T (
   SCHEDULE_NO			NUMBER				NOT NULL,
   USER_NO				NUMBER				NOT NULL,
   TITLE				VARCHAR2(50 BYTE)	NOT NULL,
   CONTENTS				VARCHAR2(1000 BYTE)	NULL,
   REMINDER				NUMBER		  		NULL,
   START_DATE			DATE				NOT NULL,
   END_DATE				DATE				NULL,
    CONSTRAINT PK_SCHEDULE_T PRIMARY KEY (SCHEDULE_NO),
	CONSTRAINT FK_SCHEDULE_USER_NO FOREIGN KEY (USER_NO)
	REFERENCES USER_T(USER_NO) ON DELETE CASCADE
);

INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'admin', 1, STANDARD_HASH('admin', 'SHA256'), 'admin@bigbrother.com', 'ë¹…ë¸Œë¼ë”', 'man', '010-1111-1111', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester1', 0, STANDARD_HASH('1111', 'SHA256'), 'tester1@example.com', 'í…ŒìŠ¤í„°1', 'man', '010-1111-1111', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester2', 0, STANDARD_HASH('2222', 'SHA256'), 'tester2@example.com', 'í…ŒìŠ¤í„°2', 'man', '010-2222-2222', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester3', 0, STANDARD_HASH('3333', 'SHA256'), 'tester3@example.com', 'í…ŒìŠ¤í„°3', 'man', '010-3333-3333', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester4', 0, STANDARD_HASH('4444', 'SHA256'), 'tester4@example.com', 'í…ŒìŠ¤í„°4', 'man', '010-4444-4444', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester5', 0, STANDARD_HASH('5555', 'SHA256'), 'tester5@example.com', 'í…ŒìŠ¤í„°5', 'man', '010-5555-5555', CURRENT_DATE, CURRENT_DATE, NULL);
INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'tester6', 0, STANDARD_HASH('6666', 'SHA256'), 'tester6@example.com', 'í…ŒìŠ¤í„°6', 'man', '010-6666-6666', CURRENT_DATE, CURRENT_DATE, NULL);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '»çÁø ÃÔ¿µ ±â¼ú', 'ÃÊº¸ÀÚµµ ½±°Ô µû¶óÇÒ ¼ö ÀÖ´Â ±âº»ÀûÀÎ »çÁø ÃÔ¿µ ±â¼úÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '°¡Á¤¿ë °¡µå´× ÆÁ', 'Áý¿¡¼­ ½ÇÃµÇÒ ¼ö ÀÖ´Â °£´ÜÇÏ°í È¿°úÀûÀÎ °¡µå´× ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'µå·Ð Á¶Á¾ ±â¼ú', 'µå·Ð ºñÇà ±â¼ú ¹× Á¶Á¾ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, 'À¯Æ©ºê Ã¤³Î ¼º°ø Àü·«', '¼º°øÀûÀÎ À¯Æ©ºê Ã¤³Î ¿î¿µÀ» À§ÇÑ Àü·«°ú ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, '¼öÁ·°ü °ü¸®¹ý', 'Áý¿¡¼­ ¼öÁ·°üÀ» °ü¸®ÇÏ´Â ¹ý°ú ÇÊ¿äÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, '½º¸¶Æ® È¨ µð¹ÙÀÌ½º', '½º¸¶Æ® È¨ µð¹ÙÀÌ½º¸¦ ÅëÇÑ Áý¾ÈÀÇ Æí¸®ÇÑ »ýÈ°À» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ Á¦ÀÛ ºñÇÏÀÎµå', '¿µÈ­ Á¦ÀÛ °úÁ¤°ú ±× µÚ¿¡ ¼û°ÜÁø ÀÌ¾ß±â¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '½Ç³» Å¬¶óÀÌ¹Ö ÆÁ', '½Ç³» Å¬¶óÀÌ¹ÖÀ» Áñ±â±â À§ÇÑ ±âÃÊ ÆÁ°ú ±â¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, '°³ÀÎ ±ÝÀ¶ °ü¸®', 'È¿°úÀûÀÎ °³ÀÎ ±ÝÀ¶ °ü¸® ¹æ¹ýÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎ ±âÃÊ', '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎÀ» ½ÃÀÛÇÏ´Â µ¥ ÇÊ¿äÇÑ ±âÃÊ Áö½ÄÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'È­»ó È¸ÀÇ ÆÁ', 'È¿°úÀûÀÎ È­»ó È¸ÀÇ¸¦ À§ÇÑ ÆÁ°ú Å×Å©´ÐÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ã¥ ÃßÃµ ¸ñ·Ï', 'ÀÌ¹ø ´Þ¿¡ ÀÐ±â ÁÁÀº Ã¥ ¸ñ·ÏÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ ÃßÃµ', 'ÁÖ¸»¿¡ º¼¸¸ÇÑ ¿µÈ­ ÃßÃµ ¸ñ·ÏÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'Ä·ÇÎ °¡ÀÌµå', 'ÃÊº¸ÀÚ¸¦ À§ÇÑ Ä·ÇÎ ÁØºñ °¡ÀÌµåÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'IT ±â¼ú µ¿Çâ', 'ÃÖ½Å IT ±â¼ú Æ®·»µå¸¦ ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¿ä¸® ·¹½ÃÇÇ', 'Áý¿¡¼­ ½±°Ô ¸¸µé ¼ö ÀÖ´Â ¿ä¸® ·¹½ÃÇÇ¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'µî»ê ÆÁ', 'µî»ê ÃÊº¸ÀÚ¸¦ À§ÇÑ À¯¿ëÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'µðÁöÅÐ ¸¶ÄÉÆÃ', 'µðÁöÅÐ ¸¶ÄÉÆÃÀÇ ±âÃÊ¿¡ ´ëÇØ ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¼öÁ¦ ¸ÆÁÖ ¸¸µé±â', 'Áý¿¡¼­ ¼öÁ¦ ¸ÆÁÖ¸¦ ¸¸µå´Â ¹æ¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'ÀÚµ¿Â÷ Á¤ºñ ÆÁ', 'ÀÚµ¿Â÷¸¦ Á÷Á¢ Á¤ºñÇÏ´Â ¹æ¹ýÀ» ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'Á¤¿ø °¡²Ù±âÀÇ ¸ðµç °Í', 'Á¤¿øÀ» °¡²Ù´Â µ¥ ÇÊ¿äÇÑ ÆÁ°ú ¾ÆÀÌµð¾î¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'ÀÚÀü°Å ¿©Çà ÁØºñÇÏ±â', 'ÀÚÀü°Å ¿©ÇàÀ» À§ÇÑ ÁØºñ¹°°ú ÁÖÀÇ»çÇ×À» ¾Ë·Áµå¸³´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, 'Ä¿ÇÇ ·Î½ºÆÃÀÇ ±â¼ú', 'Áý¿¡¼­ Ä¿ÇÇ ·Î½ºÆÃÀ» ÇÏ´Â ¹æ¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '¼öÁ¦ ¸ÆÁÖ ¸¸µé±â', 'Áý¿¡¼­ ¼öÁ¦ ¸ÆÁÖ¸¦ ¸¸µå´Â °úÁ¤À» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'ÃÊº¸ÀÚ¸¦ À§ÇÑ Å×´Ï½º °¡ÀÌµå', 'Å×´Ï½º ÃÊº¸ÀÚ°¡ ¾Ë¾Æ¾ß ÇÒ ±âÃÊ Áö½Ä°ú ÆÁÀ» Á¦°øÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¸ð¹ÙÀÏ °ÔÀÓ °³¹ß ÀÔ¹®', '¸ð¹ÙÀÏ °ÔÀÓ °³¹ßÀ» ½ÃÀÛÇÏ´Â ¹æ¹ý°ú ÇÊ¿äÇÑ µµ±¸¿¡ ´ëÇØ ¼³¸íÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'µµ½Ã¶ô ÆÐÅ· ¾ÆÀÌµð¾î', '¸ÅÀÏÀÇ µµ½Ã¶ôÀ» »õ·Ó°í ¸ÀÀÖ°Ô ÆÐÅ·ÇÏ´Â ¹æ¹ýÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'ÃÊº¸ÀÚ¸¦ À§ÇÑ ÄÚµù ½ºÄð', 'ÇÁ·Î±×·¡¹ÖÀ» Ã³À½ ½ÃÀÛÇÏ´Â »ç¶÷µéÀ» À§ÇÑ ±âº» °¡ÀÌµå.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '»çÁø ÃÔ¿µ ±â¼ú', 'ÃÊº¸ÀÚµµ ½±°Ô µû¶óÇÒ ¼ö ÀÖ´Â ±âº»ÀûÀÎ »çÁø ÃÔ¿µ ±â¼úÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '°¡Á¤¿ë °¡µå´× ÆÁ', 'Áý¿¡¼­ ½ÇÃµÇÒ ¼ö ÀÖ´Â °£´ÜÇÏ°í È¿°úÀûÀÎ °¡µå´× ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'µå·Ð Á¶Á¾ ±â¼ú', 'µå·Ð ºñÇà ±â¼ú ¹× Á¶Á¾ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, 'À¯Æ©ºê Ã¤³Î ¼º°ø Àü·«', '¼º°øÀûÀÎ À¯Æ©ºê Ã¤³Î ¿î¿µÀ» À§ÇÑ Àü·«°ú ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, '¼öÁ·°ü °ü¸®¹ý', 'Áý¿¡¼­ ¼öÁ·°üÀ» °ü¸®ÇÏ´Â ¹ý°ú ÇÊ¿äÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, '½º¸¶Æ® È¨ µð¹ÙÀÌ½º', '½º¸¶Æ® È¨ µð¹ÙÀÌ½º¸¦ ÅëÇÑ Áý¾ÈÀÇ Æí¸®ÇÑ »ýÈ°À» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ Á¦ÀÛ ºñÇÏÀÎµå', '¿µÈ­ Á¦ÀÛ °úÁ¤°ú ±× µÚ¿¡ ¼û°ÜÁø ÀÌ¾ß±â¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '½Ç³» Å¬¶óÀÌ¹Ö ÆÁ', '½Ç³» Å¬¶óÀÌ¹ÖÀ» Áñ±â±â À§ÇÑ ±âÃÊ ÆÁ°ú ±â¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, '°³ÀÎ ±ÝÀ¶ °ü¸®', 'È¿°úÀûÀÎ °³ÀÎ ±ÝÀ¶ °ü¸® ¹æ¹ýÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎ ±âÃÊ', '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎÀ» ½ÃÀÛÇÏ´Â µ¥ ÇÊ¿äÇÑ ±âÃÊ Áö½ÄÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'È­»ó È¸ÀÇ ÆÁ', 'È¿°úÀûÀÎ È­»ó È¸ÀÇ¸¦ À§ÇÑ ÆÁ°ú Å×Å©´ÐÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ã¥ ÃßÃµ ¸ñ·Ï', 'ÀÌ¹ø ´Þ¿¡ ÀÐ±â ÁÁÀº Ã¥ ¸ñ·ÏÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ ÃßÃµ', 'ÁÖ¸»¿¡ º¼¸¸ÇÑ ¿µÈ­ ÃßÃµ ¸ñ·ÏÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'Ä·ÇÎ °¡ÀÌµå', 'ÃÊº¸ÀÚ¸¦ À§ÇÑ Ä·ÇÎ ÁØºñ °¡ÀÌµåÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'IT ±â¼ú µ¿Çâ', 'ÃÖ½Å IT ±â¼ú Æ®·»µå¸¦ ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¿ä¸® ·¹½ÃÇÇ', 'Áý¿¡¼­ ½±°Ô ¸¸µé ¼ö ÀÖ´Â ¿ä¸® ·¹½ÃÇÇ¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'µî»ê ÆÁ', 'µî»ê ÃÊº¸ÀÚ¸¦ À§ÇÑ À¯¿ëÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'µðÁöÅÐ ¸¶ÄÉÆÃ', 'µðÁöÅÐ ¸¶ÄÉÆÃÀÇ ±âÃÊ¿¡ ´ëÇØ ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¼öÁ¦ ¸ÆÁÖ ¸¸µé±â', 'Áý¿¡¼­ ¼öÁ¦ ¸ÆÁÖ¸¦ ¸¸µå´Â ¹æ¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'ÀÚµ¿Â÷ Á¤ºñ ÆÁ', 'ÀÚµ¿Â÷¸¦ Á÷Á¢ Á¤ºñÇÏ´Â ¹æ¹ýÀ» ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'Á¤¿ø °¡²Ù±âÀÇ ¸ðµç °Í', 'Á¤¿øÀ» °¡²Ù´Â µ¥ ÇÊ¿äÇÑ ÆÁ°ú ¾ÆÀÌµð¾î¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'ÀÚÀü°Å ¿©Çà ÁØºñÇÏ±â', 'ÀÚÀü°Å ¿©ÇàÀ» À§ÇÑ ÁØºñ¹°°ú ÁÖÀÇ»çÇ×À» ¾Ë·Áµå¸³´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, 'Ä¿ÇÇ ·Î½ºÆÃÀÇ ±â¼ú', 'Áý¿¡¼­ Ä¿ÇÇ ·Î½ºÆÃÀ» ÇÏ´Â ¹æ¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '¼öÁ¦ ¸ÆÁÖ ¸¸µé±â', 'Áý¿¡¼­ ¼öÁ¦ ¸ÆÁÖ¸¦ ¸¸µå´Â °úÁ¤À» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'ÃÊº¸ÀÚ¸¦ À§ÇÑ Å×´Ï½º °¡ÀÌµå', 'Å×´Ï½º ÃÊº¸ÀÚ°¡ ¾Ë¾Æ¾ß ÇÒ ±âÃÊ Áö½Ä°ú ÆÁÀ» Á¦°øÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¸ð¹ÙÀÏ °ÔÀÓ °³¹ß ÀÔ¹®', '¸ð¹ÙÀÏ °ÔÀÓ °³¹ßÀ» ½ÃÀÛÇÏ´Â ¹æ¹ý°ú ÇÊ¿äÇÑ µµ±¸¿¡ ´ëÇØ ¼³¸íÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'µµ½Ã¶ô ÆÐÅ· ¾ÆÀÌµð¾î', '¸ÅÀÏÀÇ µµ½Ã¶ôÀ» »õ·Ó°í ¸ÀÀÖ°Ô ÆÐÅ·ÇÏ´Â ¹æ¹ýÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'ÃÊº¸ÀÚ¸¦ À§ÇÑ ÄÚµù ½ºÄð', 'ÇÁ·Î±×·¡¹ÖÀ» Ã³À½ ½ÃÀÛÇÏ´Â »ç¶÷µéÀ» À§ÇÑ ±âº» °¡ÀÌµå.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '»çÁø ÃÔ¿µ ±â¼ú', 'ÃÊº¸ÀÚµµ ½±°Ô µû¶óÇÒ ¼ö ÀÖ´Â ±âº»ÀûÀÎ »çÁø ÃÔ¿µ ±â¼úÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '°¡Á¤¿ë °¡µå´× ÆÁ', 'Áý¿¡¼­ ½ÇÃµÇÒ ¼ö ÀÖ´Â °£´ÜÇÏ°í È¿°úÀûÀÎ °¡µå´× ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'µå·Ð Á¶Á¾ ±â¼ú', 'µå·Ð ºñÇà ±â¼ú ¹× Á¶Á¾ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, 'À¯Æ©ºê Ã¤³Î ¼º°ø Àü·«', '¼º°øÀûÀÎ À¯Æ©ºê Ã¤³Î ¿î¿µÀ» À§ÇÑ Àü·«°ú ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, '¼öÁ·°ü °ü¸®¹ý', 'Áý¿¡¼­ ¼öÁ·°üÀ» °ü¸®ÇÏ´Â ¹ý°ú ÇÊ¿äÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, '½º¸¶Æ® È¨ µð¹ÙÀÌ½º', '½º¸¶Æ® È¨ µð¹ÙÀÌ½º¸¦ ÅëÇÑ Áý¾ÈÀÇ Æí¸®ÇÑ »ýÈ°À» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ Á¦ÀÛ ºñÇÏÀÎµå', '¿µÈ­ Á¦ÀÛ °úÁ¤°ú ±× µÚ¿¡ ¼û°ÜÁø ÀÌ¾ß±â¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, '½Ç³» Å¬¶óÀÌ¹Ö ÆÁ', '½Ç³» Å¬¶óÀÌ¹ÖÀ» Áñ±â±â À§ÇÑ ±âÃÊ ÆÁ°ú ±â¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, '°³ÀÎ ±ÝÀ¶ °ü¸®', 'È¿°úÀûÀÎ °³ÀÎ ±ÝÀ¶ °ü¸® ¹æ¹ýÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎ ±âÃÊ', '¸ð¹ÙÀÏ ¾Û µðÀÚÀÎÀ» ½ÃÀÛÇÏ´Â µ¥ ÇÊ¿äÇÑ ±âÃÊ Áö½ÄÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'È­»ó È¸ÀÇ ÆÁ', 'È¿°úÀûÀÎ È­»ó È¸ÀÇ¸¦ À§ÇÑ ÆÁ°ú Å×Å©´ÐÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'Ä·ÇÎ ÇÊ¼ö ¾ÆÀÌÅÛ', 'Ä·ÇÎÀ» ¶°³ª±â Àü¿¡ ÁØºñÇØ¾ß ÇÒ ÇÊ¼ö ¾ÆÀÌÅÛµéÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'Ã¥ ÃßÃµ ¸ñ·Ï', 'ÀÌ¹ø ´Þ¿¡ ÀÐ±â ÁÁÀº Ã¥ ¸ñ·ÏÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¿µÈ­ ÃßÃµ', 'ÁÖ¸»¿¡ º¼¸¸ÇÑ ¿µÈ­ ÃßÃµ ¸ñ·ÏÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'Ä·ÇÎ °¡ÀÌµå', 'ÃÊº¸ÀÚ¸¦ À§ÇÑ Ä·ÇÎ ÁØºñ °¡ÀÌµåÀÔ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 5, 'IT ±â¼ú µ¿Çâ', 'ÃÖ½Å IT ±â¼ú Æ®·»µå¸¦ ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 6, '¿ä¸® ·¹½ÃÇÇ', 'Áý¿¡¼­ ½±°Ô ¸¸µé ¼ö ÀÖ´Â ¿ä¸® ·¹½ÃÇÇ¸¦ °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 1, 'µî»ê ÆÁ', 'µî»ê ÃÊº¸ÀÚ¸¦ À§ÇÑ À¯¿ëÇÑ ÆÁÀ» °øÀ¯ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (2, BOARD_SEQ.NEXTVAL, 2, 'µðÁöÅÐ ¸¶ÄÉÆÃ', 'µðÁöÅÐ ¸¶ÄÉÆÃÀÇ ±âÃÊ¿¡ ´ëÇØ ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (3, BOARD_SEQ.NEXTVAL, 3, '¼öÁ¦ ¸ÆÁÖ ¸¸µé±â', 'Áý¿¡¼­ ¼öÁ¦ ¸ÆÁÖ¸¦ ¸¸µå´Â ¹æ¹ýÀ» ¼Ò°³ÇÕ´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOARD_T (CATE_NO, BOARD_NO, USER_NO, TITLE, CONTENTS, HIT, CREATE_DT, MODIFY_DT)
VALUES (1, BOARD_SEQ.NEXTVAL, 4, 'ÀÚµ¿Â÷ Á¤ºñ ÆÁ', 'ÀÚµ¿Â÷¸¦ Á÷Á¢ Á¤ºñÇÏ´Â ¹æ¹ýÀ» ¾Ë¾Æº¾´Ï´Ù.', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì–˜ ë‚˜ìœ ì• ì—ìš”', 'ì§„ì§œ ë‚˜ìœ ì• ìž„', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì•„ë¬´íŠ¼ ì§„ì§œ ë‚˜ìœ ì• ìž„', 'ì§„ì§œë¡œ ë‚˜ë¹ ìš”', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì–˜ ë‚˜ìœë§ í•´ìš”', 'ë„ˆë¬´ ë¬´ì„œì›Œìš”', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì–˜ëŠ” ê·¸ëƒ¥ ë‚´ê°€ ì‹«ì–´ìš”', 'ë°´ì¢€', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ë‚´ê°€ ì–˜ ë‚˜ìœ ì§“ í•˜ëŠ” ê±° ë´¤ì–´ìš”', 'ë„ˆë¬´ ë¬´ì„œìš´ ì‚¬ëžŒì´ì—ìš”', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì‹ ê³ ê°ì´ì•¼', 'ì´ëŸ° ì• ëŠ” ê²½ì°°ì´ ìž¡ì•„ê°€ì•¼í•¨', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ë‚˜ë„ ì‹ ê³ í•´ë³¼ëž˜', 'ì‹ ê³  ìž¬ë°Œì–´ìš”', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ì–˜ ìžê¾¸ ìžê¾¸', 'ìžê¾¸ ìžê¾¸ ìžê¾¸ ìžê¾¸...', CURRENT_DATE);
INSERT INTO REPORT_T VALUES(REPORT_SEQ.NEXTVAL, MOD(ABS(DBMS_RANDOM.RANDOM), 4) + 2, NULL, MOD(ABS(DBMS_RANDOM.RANDOM), 15) + 1, 'ë‚˜ ë°´ ì¢€ í•´ì¤˜ìš”', 'ë‚˜ ìžì‹ ì´ ë¬´ì„œì›Œìš”', CURRENT_DATE);

COMMIT;
